# Red Neuronal Simple

En este notebook programaremos una red neuronal simple (perceptron) utilizando numpy. El objetivo es que comprendamos el funcionamiento del perceptrón y que practiquemos la programación en Python. En la siguiente figura se encuentra una representación del perceptrón.


<img src="https://github.com/irvingvasquez/cv2course_intro_nn/blob/master/files/simple_nn_notebook.png?raw=1">

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/irvingvasquez/cv2course_intro_nn/blob/master/02_red_neuronal_simple.ipynb)

@juan1rving


In [3]:
# Cargamos paquetes
import numpy as np

## Calcular producto punto

El primer paso es calcular el logit, *h*, a partir del producto punto. La fórmula explícita es la siguiente:

$$ h = W X +b $$

In [2]:
# TODO: Implementar la función H

def function_h(X, W, b):
    suma = 0
    for i in range(len(X)):
        suma += X[i] * W[i]
    suma += b
    return suma

## Función de activación

Para este ejemplo utilizaremos la función sigmoide como función de activación.

$$ f(x) =  \frac{\mathrm{1} }{\mathrm{1} + e^{-x} }  $$

In [6]:
# TODO: Implementar la función de activación.
# En este ejemplo utilizaremos la función sigmoide.

def sigmoid(x):
    sg = 1 / (1 + np.exp(-x))
    return sg

## Probar la red

Ahora definamos unos pesos y veamos el resultado de una pasada frontal (fordward pass).

In [7]:
# Definamos unos pesos y sesgo
inputs = np.array([0.7, -0.3])
weights = np.array([0.1, 0.8])
bias = -0.1

# Pasada frontal
h = function_h(inputs,weights,bias)
output = sigmoid(h)

print('Output:')
print(output)


Output:
0.4329070950345457


## Pruebas extra

- Define una función de activación de tipo escalón, "heaviside".  
- ¿Cuáles son los pesos que definen una función OR?

In [ ]:
# TODO: Completar el código
def escalon(x):
    if x < 0:
        return 0
    elif x >= 0:
        return 1

In [9]:
# TODO: Realizar el pase frontal y muesta los resultados que concuerdan con la función OR

# Define the weights and bias for the OR function
weights = np.array([1, 1])
bias = -0.5

# Inputs for the OR function
test_inputs = np.array([(0, 0), (0, 1), (1, 0), (1, 1)])

# Calculate the linear combination (dot product) and apply the step function
linear_combination = np.dot(test_inputs, weights) + bias
output = (linear_combination >= 0).astype(int)

# Define the correct outputs for the OR function
correct_outputs = np.array([0, 1, 1, 1])

# Check if the outputs match the correct outputs
is_correct = np.array_equal(output, correct_outputs)

# Print the results
print("Inputs:")
print(test_inputs)
print("\nLinear Combination:")
print(linear_combination)
print("\nActivation Output:")
print(output)
print("\nCorrect Outputs:")
print(correct_outputs)

if is_correct:
    print("\nAll results match the OR function.")
else:
    print("\nSome results do not match the OR function.")

Inputs:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Linear Combination:
[-0.5  0.5  0.5  1.5]

Activation Output:
[0 1 1 1]

Correct Outputs:
[0 1 1 1]

All results match the OR function.
